### ISSUE TITLE
Updated protocol docs for new LIFX Switch configuration options

### ISSUE THREAD

**Issue by Djelibeybi** [LIFX/public-protocol#6]
Hey folks,

Firstly, congratulations on releasing 3.90 for the Switch. This is a huge improvement in functionality and user experience and it's awesome. 

Having said that, I am a little disappointed that the LAN protocol specification on GitHub and corresponding documentation at https://lan.developer.lifx.com/docs/the-lifx-switch weren't updated when the firmaware and 4.11 app went GA.

I know I'm eager to add support for this to the third-party library/API to which I contribute as well as using it to improve the integration with other open source automation platforms like Home Assistant. 

Would it be possible to get some sort of timeframe for when the new packet definitions will be added? It would be great if these packets included a way to return the number of relays/buttons available on the device.

**Comment by redding1** [comment]
Could you please help provide some context to which API/features you think would be useful to make public? For example:

- Setting RGB/HSBK colour of Switch Buttons
- Request the total number of relays/buttons connected

(And thank you!) :)

**Comment by Djelibeybi** [comment]
For your first item, let's make it simpler and more explicit:

1. The Switch should export each button as a LIFX bulb that responds as expected to the existing Light messages.

For the relays/buttons, we'd need at least the following:

1. Get, set and state whether a relay is wired
2. Get, set and state whether a relay controls a LIFX or non-LIFX device
3. Get, set and state the label for a relay set to control a non-LIFX device
4. Get, set and state the target for each button, which should include a `null` target which removes any existing target

Finally, providing a non-proprietary push mechanism like an MQTT client that can be configured via get, set and state messages would expotentially increase the amount of compatible ecosystems and enable unlimited user-specific  control.

**Comment by redding1** [comment]
Thanks for the additional details @Djelibeybi. Perhaps you can explain why you need each Button to act as a LIFX Bulb, rather than just the ability to set backlight color? I suggest initially focusing on the use cases, and what you need to implement those use cases.

**Comment by Djelibeybi** [comment]
Having each button also be a LIFX bulb means they would instantaenously be fully supported by all existing LAN protocol implementations which means that any app that supports LIFX bulbs can now control the bulb-in-a-button. 

As for the use-cases, the official "what I told my husband and admit in public" reason is to match the same colour and relative brightness as the light(s) the button controls and to be able to keep buttons that control LIFX devices illuminated when their corresponding bulb is on.

The real reason is so that I can add them to Razer Chroma and Light DJ Pro so they too can be part of my already over-the-top, make-it-stop, the-light-it-burns whole house disco party experience.

**Comment by Djelibeybi** [comment]
btw, MQTT is a serving suggestion at best, but provided as an example as it is supported by a broad range of IoT platforms and ecosystems.

MVP is a mechanism by which the Switch be configured to tell something via some method that a button has been pushed in a particular way, with each variable configurable at least on a per-button basis, if not per-event-type-per-button.

**Comment by Djelibeybi** [comment]
Any chance we can at least get the LAN protocol docs updated with the new terminal/button messages?

**Comment by dntj** [comment]
I've just pushed https://github.com/LIFX/public-protocol/commit/78fef2d8b7ae828bdffb2d6b11eb3f56d2a2b5d3 which exposes the new messages.  We're working on getting these documented in the LAN API docs too.
